import 'package:bookaway_flutter/model/BookModel.dart';

List<BookModel> books = [
  BookModel(
      1,
      "Don Quixote",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      2,
      "Пикник на обочине",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      3,
      "Jo Nesbø - Snowman",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Taken",
      1),
  BookModel(
      4,
      "Tom Sawyer",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      5,
      "Peter Watts - Blindsight",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Taken",
      1),
  BookModel(
      6,
      "Kotlin in Action",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      7,
      "Financial Intelligence",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      8,
      "The One Minute Manager",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
  BookModel(
      9,
      "Headfirst Android Development",
      DateTime.now().toString(),
      DateTime.now().toString(),
      DateTime.now().toString(),
      1,
      "Available",
      null),
];
